### ISSUE TITLE
Bourne dependency breaks engine specification of 4.x.x

### ISSUE THREAD

**Issue by JustinBeaudry** [hapijs/statehood#57]
The package `bourne` that was introduced a short time ago breaks node versions `4.x.x` as the rest operator is not supported in node `4.x.x` without a flag.

```shell
/var/node/cthulhu/node_modules/bourne/lib/index.js:7
 exports.parse = function (text, ...args) {
                                 ^^^
SyntaxError: Unexpected token ...
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:373:25)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.cls_wrapMethod [as _load (/var/node/cthulhu/node_modules/newrelic/lib/shimmer.js:257:38)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/var/node/cthulhu/node_modules/statehood/lib/index.js:6:16)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.cls_wrapMethod [as _load] (/var/node/cthulhu/node_modules/newrelic/lib/shimmer.js:257:38)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/var/node/cthulhu/node_modules/hapi/lib/connection.js:14:19)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.cls_wrapMethod [as _load] (/var/node/cthulhu/node_modules/newrelic/lib/shimmer.js:257:38)
```

**Comment by JustinBeaudry** [comment]
Referencing the issue here since this package specifies supported node version `4.x.x` in it's package.json.

**Comment by hueniverse** [comment]
I'll fix the engines reference but not the actual issue. hapi v16 requires node v6. No active hapi components supports hapi 4 anymore.

**Comment by hueniverse** [comment]
Closing since all previous versions are being deprecated and no longer supported. To avoid this issue, lock your dependency version to the last known good.
